name: Build
on:
  push:
    branches: [main,dev]
      
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:latest
        ports:
          # Opens tcp port 6379 on the host and service container
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Start Containers
        run: docker-compose -f "docker-compose.yml" up --build  --exit-code-from zap_app
   
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TQS-G11_Zap_Backend
        
      - name: Stop containers
        if: always()
        run: docker-compose down
